// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV109WweJpaDjSm1agp8TjXkUBWFaaVzA',
    appId: '1:482271504503:web:c99f56dbd129cb80163e72',
    messagingSenderId: '482271504503',
    projectId: 'quantum-8a884',
    authDomain: 'quantum-8a884.firebaseapp.com',
    storageBucket: 'quantum-8a884.firebasestorage.app',
    measurementId: 'G-99HEMTN882',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKPR0SeQkRN5OPP6dG6Nb84E8luqzUnk',
    appId: '1:482271504503:android:b67d253d4a2c1435163e72',
    messagingSenderId: '482271504503',
    projectId: 'quantum-8a884',
    storageBucket: 'quantum-8a884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEK_bYDLVEQmNJ5fL3k92BH7ftQzMJw3k',
    appId: '1:482271504503:ios:6d01949b94ac8268163e72',
    messagingSenderId: '482271504503',
    projectId: 'quantum-8a884',
    storageBucket: 'quantum-8a884.firebasestorage.app',
    iosBundleId: 'com.example.quantum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEK_bYDLVEQmNJ5fL3k92BH7ftQzMJw3k',
    appId: '1:482271504503:ios:6d01949b94ac8268163e72',
    messagingSenderId: '482271504503',
    projectId: 'quantum-8a884',
    storageBucket: 'quantum-8a884.firebasestorage.app',
    iosBundleId: 'com.example.quantum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV109WweJpaDjSm1agp8TjXkUBWFaaVzA',
    appId: '1:482271504503:web:1cde0ad5960a59ef163e72',
    messagingSenderId: '482271504503',
    projectId: 'quantum-8a884',
    authDomain: 'quantum-8a884.firebaseapp.com',
    storageBucket: 'quantum-8a884.firebasestorage.app',
    measurementId: 'G-JJGYYSVFRC',
  );
}
